[build-system]
requires = ["setuptools>=42",
            "wheel"]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
tests = ["pytest",]

[tool.pytest.ini_options]
minversion = "6.0"
# addopts = "-ra -q"
testpaths = ["test",]

[tool.cibuildwheel]
build-verbosity = 3
test-requires = "pytest"
test-command = "pytest {project}/test || true"

[tool.cibuildwheel.linux]
before-all = ["yum install -y bison flex libicu-devel readline-devel",
              "source scripts/ensure_bison_installed.sh",
              "source scripts/ensure_icu_installed.sh Linux",
              "cd libhfst_src/",
              "autoreconf -fvi",
              "./configure --with-unicode-handler=icu",
              "make -C back-ends",
              "make -C libhfst",
              "cd ..",
]
manylinux-x86_64-image = "manylinux2014"
manylinux-i686-image = "manylinux2014"
manylinux-aarch64-image = "manylinux2014"
manylinux-ppc64le-image = "manylinux2014"
manylinux-s390x-image = "manylinux2014"

# Before Python 3.10, manylinux2010 is the most compatible
[[tool.cibuildwheel.overrides]]
select = "cp3?-*"
manylinux-x86_64-image = "manylinux2010"
manylinux-i686-image = "manylinux2010"
manylinux-aarch64-image = "manylinux2010"
manylinux-ppc64le-image = "manylinux2010"
manylinux-s390x-image = "manylinux2010"

[[tool.cibuildwheel.overrides]]
select = "*musllinux*"
before-all = ["apk add bison flex icu-dev readline-dev",
              "source scripts/ensure_bison_installed.sh",
              "source scripts/ensure_icu_installed.sh Linux",
              "cd libhfst_src/",
              "autoreconf -fvi",
              "./configure --with-unicode-handler=icu",
              "make -C back-ends",
              "make -C libhfst",
              "cd ..",
]

[tool.cibuildwheel.macos]
before-all = "bash scripts/cibw_before_all_macos.sh"
environment = { MACOSX_DEPLOYMENT_TARGET="10.9" }
# repair-wheel-command = "delocate-listdeps {wheel} && delocate-wheel --require-archs {delocate_archs} -w {dest_dir} {wheel} && bash scripts/macos_fi {dest_dir} {wheel}"

[tool.cibuildwheel.windows]
before-all = "C:\\msys64\\msys2_shell.cmd -mingw64 -defterm -here -full-path -no-start -shell bash scripts/cibw_before_all_windows.sh"
