[project]
requires-python = ">=3.6"

[build-system]
requires = ["setuptools>=42",
            "wheel"]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
tests = ["pytest",]

[tool.pytest.ini_options]
minversion = "6.0"
# addopts = "-ra -q"
testpaths = ["test",]

[tool.cibuildwheel]
build-verbosity = 3
skip = ["cp27-*", "cp35-*", "pp*"]
test-requires = "pytest"
test-command = "pytest {project}/test || true"

[tool.cibuildwheel.linux]
before-all = "bash scripts/cibw_before_all_linux.sh"
manylinux-pypy_x86_64-image = "manylinux2010"  # 2014 unavailable
manylinux-x86_64-image = "manylinux2014"
manylinux-i686-image = "manylinux2014"
manylinux-aarch64-image = "manylinux2014"
manylinux-ppc64le-image = "manylinux2014"
manylinux-s390x-image = "manylinux2014"

[tool.cibuildwheel.macos]
before-all = "bash scripts/cibw_before_all_macos.sh"
environment = { MACOSX_DEPLOYMENT_TARGET="10.9" }
# repair-wheel-command = "delocate-listdeps {wheel} && delocate-wheel --require-archs {delocate_archs} -w {dest_dir} {wheel} && bash scripts/macos_fi {dest_dir} {wheel}"

[tool.cibuildwheel.windows]
before-all = "C:\\msys64\\msys2_shell.cmd -mingw64 -defterm -here -full-path -no-start -shell bash scripts/cibw_before_all_windows.sh"
