#!/usr/bin/env python3
"""
To use this script as a local pre-commit check...
    1) Symlink (or copy) this file to .git/hooks/
    2) Ensure that it is executable (chmod +x .git/hooks/pre-commit).
"""

import subprocess
import sys

sys.stdin = open('/dev/tty')

print(f'Running {__file__} ...', file=sys.stderr)

diff = subprocess.run(['git', 'diff', 'VERSION'],
                      stdout=subprocess.PIPE,
                      universal_newlines=True).stdout.strip()
with open('VERSION') as f:
    new_version = f.read().strip()
diff_msg = f' with v{new_version}' if diff else ''

if diff:
    print(f'The version number in `setup.py` has changed to {new_version}. '
          'It is recommended that you leave version numbering up to this '
          'pre-commit script. How would you like to proceed?')
else:
    print('How would you like to proceed?')
response = input('\t(C) Cancel/abort commit.\n'
                 f'\t(I) Ignore (commit as-is{diff_msg})\n'
                 '\t(R) Make a (R)elease (auto-bump release version)\n'
                 '\t(T) Make a (T)est release (auto-bump beta version)\n'
                 '\t (c/i/r/T) > ')

if response in {'C', 'c'}:
    sys.exit(1)
elif response in {'I', 'i'}:
    sys.exit(0)
elif response in {'R', 'r'}:
    completed = subprocess.run(['./scripts/bump_version.py'],
                               stderr=subprocess.PIPE,
                               stdout=subprocess.PIPE,
                               universal_newlines=True)
    subprocess.run(['git', 'add', 'VERSION'])
    print(completed.stderr)
    autoversion = completed.stdout.strip()
    print(f'Version set to {autoversion}')
    sys.exit(0)
elif response in {'T', 't', ''}:
    completed = subprocess.run(['./scripts/bump_version.py', '--test'],
                               stderr=subprocess.PIPE,
                               stdout=subprocess.PIPE,
                               universal_newlines=True)
    subprocess.run(['git', 'add', 'VERSION'])
    print(completed.stderr)
    autoversion = completed.stdout.strip()
    print(f'Version set to {autoversion}')
    sys.exit(0)
else:
    print('Unrecognized option ({response}). Aborting...')
    sys.exit(1)
