name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    environment: Build
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]  # windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.9'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel

      - name: Upgrade setuptools, twine and wheel
        run: |
          python -m pip install --upgrade setuptools twine wheel

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BEFORE_ALL_MACOS: "{package}/cibw_before_all_macos.sh"
          CIBW_BEFORE_ALL_LINUX: "{package}/cibw_before_all_linux.sh"
          CIBW_BUILD_VERBOSITY: 3
          CIBW_SKIP: cp27-* cp35-* cp*-win*

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
