name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install/compile dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          apt install swig

      - name: Install/compile dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install swig

      - name: Install/compile dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install swig

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.8.0

      - name: Install Visual C++ for Python 2.7
        if: runner.os == 'Windows'
        run: |
          choco install vcpython27 -f -y

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_SKIP: cp27-* cp35-* cp*-win*

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
