name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    environment: Build
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.9'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel

      - name: Upgrade setuptools, twine and wheel
        run: |
          python -m pip install --upgrade setuptools twine wheel

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_MANYLINUX_I686_IMAGE: manylinux2014
          CIBW_MANYLINUX_PYPY_X86_64_IMAGE: manylinux2014
          CIBW_MANYLINUX_AARCH64_IMAGE: manylinux2014
          CIBW_MANYLINUX_PPC64LE_IMAGE: manylinux2014
          CIBW_MANYLINUX_S390X_IMAGE: manylinux2014
          CIBW_BEFORE_ALL_LINUX: "{package}/cibw_before_all_linux.sh"
          CIBW_BEFORE_ALL_MACOS: "{package}/cibw_before_all_macos.sh"
          CIBW_BEFORE_ALL_WINDOWS: "bash {package}/cibw_before_all_windows.sh"
          CIBW_BUILD_VERBOSITY: 3
          CIBW_SKIP: cp27-* cp35-* pp27-*
          CIBW_TEST_COMMAND: sh test_builds.sh python

      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          packages_dir: ./wheelhouse/
          repository_url: https://test.pypi.org/legacy/

      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          packages_dir: ./wheelhouse/

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
